### ISSUE TITLE
Ne pas effacer le website en cas d'erreur de la génération des pages statiques.

### ISSUE THREAD

**Issue by sebvallee** [haum/combot#2]
En cas d'erreur lors de la "compilation", le site de production est effacé.
Peut être envisager de garder le site avant modification dans ce genre de situation?

**Comment by matael** [comment]
Effectivement, c'est faisable, je me penche là dessus bientôt.

**Comment by jblb** [comment]
pas sur que ce soit une issue de combot mais plutôt de pelican ce truc là, non ?

**Comment by sebvallee** [comment]
C'est pas combot qui déploie, et donc delete toute l'arbo avant le déploiement? Si je m'suis trompé de dépôt, désolé!

**Comment by matael** [comment]
C'est une issue de combot, c'est lui qui lance les commandes pour régénérer le site. On peut regarder si pelican propose une option pour ce genre de chose mais sinon, je me contenterai d'implémenter le backup de l'ancien site dans combot.

**Comment by sebvallee** [comment]
C'est pas combot qui déploie, et donc delete toute l'arbo avant le déploiement? Si je m'suis trompé de dépôt, désolé!
Sur 29/07/2015 13:05:38, JbLb <notifications@github.com> a écrit :
pas sur que ce soit une issue de combot mais plutôt de pelican ce truc là, non ?
